services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 682411
      POSTGRES_DB: spring_jwt_auth